sudo: required

language: php
php:
- 5.6

services:
- docker

script:
- docker build -t amixsi/centos:latest .

after_success:
- docker tag amixsi/centos:latest amixsi/centos:"$TRAVIS_TAG";
  docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  docker push amixsi/centos;

branches:
  only:
  - /^\d+/