language: bash
services: docker

before_script:
- docker build -t amixsi/centos:5-prime .

script:
- docker run --rm -it amixsi/centos:5-prime php -v
- docker run --rm -it amixsi/centos:5-prime make -v

after_success:
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- docker push amixsi/centos:5-prime