language: bash
services: docker

before_script:
- docker build -t amixsi/centos:latest -t amixsi/centos:7.4 -t amixsi/centos:7 .

script:
- docker run --rm -it amixsi/centos bash --version
- docker run --rm -it amixsi/centos node --version
- docker run --rm -it amixsi/centos npm --version
- docker run --rm -it amixsi/centos httpd -v
- docker run --rm -it amixsi/centos php -v

after_success:
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- docker push amixsi/centos